name: POUS
channels:
  - conda-forge
  - default
dependencies:
  - geopandas
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - netcdf4
  - matplotlib
  - multiprocess
  - pandas
  - pip:
    - --editable .  # bespoke POUS library code
  - pyarrow
  - python==3.11
  - bioconda::snakemake
  - xarray
