name: POUS
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - geopandas
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - matplotlib
  - multiprocess
  - pandas
  - pip:
    - --editable .  # bespoke POUS library code
  - pyarrow
  - python==3.11
  - snakemake
